### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by bobbypfreely** [soulr344/apktool_android#1]
Its like it's losing root on last step and can't find apk for the chmod cmd

**Comment by soulr344** [comment]
can you mention more info? like steps to reproduce and what does it say before failing

**Comment by bobbypfreely** [comment]
I figured it out, I just deleted all files from previous installation then reinstall went smoothly. Idk what happened, was trying to update and I think because of Android 10 permissions, root being different as well it looked for the su in wrong place.
