### ISSUE TITLE
Not work in Android 12

### ISSUE THREAD

**Issue by rofikkerneldev** [soulr344/apktool_android#2]
W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/aapt2_64/android/aarch64/aapt2_64 (defaulting to $PATH binary)
brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [aapt2, compile, --dir, /storage/emulated/0/Download/aethersx2-turnip-1447_src/res, --legacy, -o, /storage/emulated/0/Download/aethersx2-turnip-1447_src/build/resources.zip]
I: Using Apktool 2.4.2-Black-SNAPSHOT
I: Checking whether resources has changed...
I: Building resources...

**Comment by soulr344** [comment]
Seems it's an issue with APK tool itself. I can't do much unless a newer version is released. Will put a note on the readme, thanks for the heads up.
